apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-data-ms
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: psql-ms
