apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: psql
