apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-sendder-ms
spec:
  selector:
    matchLabels:
      app: psql-sendder-ms
      department: sales
  replicas: 1
  template:
    metadata:
      labels:
        app: psql-sendder-ms
        department: sales
    spec:
      containers:
      - name: psql-sendder-ms
        image: "mansurali901/postgres-sendder:v1"
        env:
        - name: "PORT"
          value: "5432"
        envFrom:
          - configMapRef:
              name: postgres-config
        volumeMounts:
          - mountPath: /var/lib/postgresql
            name: psql-data-ms
      volumes:
        - name: psql-data-ms
          persistentVolumeClaim:
            claimName: psql-data-ms

