apiVersion: v1
kind: Service
metadata:
  name: psql-sendder-ms
spec:
  type: NodePort
  selector:
    app: psql-sendder-ms
    department: sales
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
