apiVersion: v1
kind: Service
metadata:
  name: psql-sendder
spec:
  type: NodePort
  selector:
    app: psql-sendder
    department: sales
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
